<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container18gI3Tx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container18gI3Tx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container18gI3Tx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container18gI3Tx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container18gI3Tx\App_KernelDevDebugContainer([
    'container.build_hash' => '18gI3Tx',
    'container.build_id' => 'd930121a',
    'container.build_time' => 1676404850,
], __DIR__.\DIRECTORY_SEPARATOR.'Container18gI3Tx');
