<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL8lGwRL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL8lGwRL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL8lGwRL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL8lGwRL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL8lGwRL\App_KernelDevDebugContainer([
    'container.build_hash' => 'L8lGwRL',
    'container.build_id' => 'ebc507a5',
    'container.build_time' => 1678129083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL8lGwRL');
